version: "3.7"

services:
  web:
    build:
      context: .
      target: production
    image: dateflix_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
