version: "3.7"


volumes:
  db-data: {}

services:
  web:
    build:
      context: .
      target: development
    image: dateflix_api
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on:
      - db

  db:
    image: postgis/postgis:13-3.0-alpine
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
