default:
  # APP specific settings
  server: foo.com
  username: default user
  password: false
  foo: bar
  # Django Required starting settings
  DEBUG: false

  ALLOWED_HOSTS:
    - "*"

  AUTH_USER_MODEL: "app.User"

  # Application definition

  INSTALLED_APPS:
    - django.contrib.admin
    - django.contrib.auth
    - django.contrib.contenttypes
    - django.contrib.sessions
    - django.contrib.messages
    - django.contrib.staticfiles
    - corsheaders
    - rest_framework
    - dateflix_api.app

  MIDDLEWARE:
    - django.middleware.security.SecurityMiddleware
    - django.contrib.sessions.middleware.SessionMiddleware
    - corsheaders.middleware.CorsMiddleware
    - django.middleware.common.CommonMiddleware
    - django.middleware.csrf.CsrfViewMiddleware
    - django.contrib.auth.middleware.AuthenticationMiddleware
    - django.contrib.messages.middleware.MessageMiddleware
    - django.middleware.clickjacking.XFrameOptionsMiddleware

  ROOT_URLCONF: dateflix_api.urls

  TEMPLATES:
    - BACKEND: django.template.backends.django.DjangoTemplates
      DIRS: []
      APP_DIRS: true
      OPTIONS:
        context_processors:
          - django.template.context_processors.debug
          - django.template.context_processors.request
          - django.contrib.auth.context_processors.auth
          - django.contrib.messages.context_processors.messages

  WSGI_APPLICATION: dateflix_api.wsgi.application

  # Database
  # https://docs.djangoproject.com/en/2.0/ref/settings/#databases
  DATABASES:
    default:
      ENGINE: django.db.backends.sqlite3
      NAME: db.sqlite3

  # Password validation
  # https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators
  AUTH_PASSWORD_VALIDATORS:
    - NAME: django.contrib.auth.password_validation.UserAttributeSimilarityValidator
    - NAME: django.contrib.auth.password_validation.MinimumLengthValidator
    - NAME: django.contrib.auth.password_validation.CommonPasswordValidator
    - NAME: django.contrib.auth.password_validation.NumericPasswordValidator

  LANGUAGE_CODE: en-us
  TIME_ZONE: America/Sao_Paulo
  USE_I18N: true
  USE_L10N: true
  USE_TZ: true
  STATIC_URL: "/static/"

  REST_FRAMEWORK:
    DEFAULT_PAGINATION_CLASS: "rest_framework.pagination.PageNumberPagination"
    PAGE_SIZE: 10
    DEFAULT_AUTHENTICATION_CLASSES:
      - rest_framework_simplejwt.authentication.JWTAuthentication
    DEFAULT_PERMISSION_CLASSES:
      - rest_framework.permissions.IsAuthenticated

  CORS_ORIGIN_ALLOW_ALL: false
  INSTAGRAM_CLIENT_ID: xxxxxxx
  INSTAGRAM_CLIENT_SECRET: xxxxxx

development:
  DEBUG: true
  username: dev user
  foo: bar dev
  server: devserver.com
  SIGNIN_REDIRECT_URI: https://localhost:8080/signin
  SIGNUP_REDIRECT_URI: https://localhost:8080/signup
  CORS_ORIGIN_WHITELIST:
    - https://localhost:8080

production:
  server: prodserver.com
  username: prod user
  foo: bar prod
  value: this value is for django app
  SIGNIN_REDIRECT_URI: https://dateflix.netlify.app/signin
  SIGNUP_REDIRECT_URI: https://dateflix.netlify.app/signup
  CORS_ORIGIN_WHITELIST:
    - https://dateflix.netlify.app

staging:
  server: stagingserver.com
  username: staging user
  foo: bar stag

testing:
  server: stagingserver.com
  username: testing user
  foo: bar testing

customenv:
  server: customserver.com

global:
  foo: It overrides every other env
