# Generated by Django 3.0.8 on 2020-07-08 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20200707_0949"),
    ]

    operations = [
        migrations.AlterField(
            model_name="like",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="likes",
                to="app.Movie",
            ),
        ),
        migrations.AlterField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
