# Generated by Django 3.0.8 on 2020-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_profilelike"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="instagram",
            field=models.URLField(blank=True, null=True, verbose_name="instagram"),
        ),
    ]
