# Generated by Django 3.0.8 on 2020-07-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_user_instagram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(verbose_name="bio"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="instagram",
            field=models.URLField(verbose_name="instagram"),
            preserve_default=False,
        ),
    ]
