# Generated by Django 3.0.8 on 2020-07-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_auto_20200716_0859"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="netflix_id",
            field=models.IntegerField(verbose_name="Netflix Movie ID"),
            preserve_default=False,
        ),
    ]
