# Generated by Django 3.0.8 on 2020-07-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_movie_netflix_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="imdb_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="IMDB Score",
            ),
        ),
    ]
