# Generated by Django 3.0.8 on 2020-07-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_auto_20200721_0940"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="tmdb_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=3,
                null=True,
                verbose_name="TMDB Score",
            ),
        ),
    ]
