# Generated by Django 3.0.8 on 2020-07-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_movie_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="instagram_user_id",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="instagram user id"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
