# Generated by Django 3.0.8 on 2020-07-29 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_auto_20200729_0842"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday_date",
            field=models.DateField(blank=True, null=True, verbose_name="birthday date"),
        ),
    ]
