from .group import GroupViewSet  # noqa
from .like import LikeViewSet  # noqa
from .match import MatchViewSet  # noqa
from .me import MeViewSet  # noqa
from .movie import MovieViewSet  # noqa
from .playlist import PlaylistViewSet  # noqa
from .profile import ProfileViewSet  # noqa
from .profile_like import ProfileLikeViewSet  # noqa
from .token import TokenObtainPairView  # noqa
from .user import UserViewSet  # noqa
